remote_theme: pages-themes/hacker
plugins:
- jekyll-remote-theme

title: Weather Presentation - Concord, NH
description: Comprehensive Weather Map Discussion for Concord, New Hampshire - November 2025

author:
  name: Weather Analysis Project
